services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 admin password;
        mc mb --ignore-existing local/warehouse;
        echo 'Bucket ready.';
      "

  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - kafka
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic taxi-trips --partitions 1 --replication-factor 1;
        echo 'Topic taxi-trips ready.';
      "

  bronze:
    build: .
    depends_on:
      - kafka-init
      - minio
    volumes:
      - ./src:/opt/app/src
      - ./data:/opt/app/data
      - ./checkpoints:/opt/app/checkpoints
    command: python src/streaming/bronze.py

  silver:
    build: .
    depends_on:
      - bronze
    volumes:
      - ./src:/opt/app/src
      - ./data:/opt/app/data
      - ./checkpoints:/opt/app/checkpoints
    command: python src/streaming/silver.py

  gold:
    build: .
    depends_on:
      - silver
    volumes:
      - ./src:/opt/app/src
      - ./data:/opt/app/data
      - ./checkpoints:/opt/app/checkpoints
    command: python src/streaming/gold.py

volumes:
  minio-data:
